services:
  clypassbackend:
    image: clypassbackend
    build:
      context: .
      dockerfile: CLYPassBackend/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
