version: "3.8"
name: book-manager

services:
  api:
    container_name: book-manager
    image: book-manager:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:5432
    ports:
      - 5432:5432