# This is a generated file. Not intended for manual editing.
services:
  backend:
    build:
      context: "/Users/camilogato/RiderProjects/CLYPass"
      dockerfile: "CLYPassBackend/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/linux-x64/CLYPassBackend.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "clypassbackend:dev"
    ports: []
    volumes:
    - "/Users/camilogato/RiderProjects/CLYPass/CLYPassBackend:/app:rw"
    - "/Users/camilogato/RiderProjects/CLYPass:/src:rw"
    - "/Users/camilogato/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
